/**
 * Build-time generator for src/lib/blog-corpus-text.ts.
 *
 * Reads README.md + docs/handbook.md from the repo root and writes them
 * as JSON-quoted string constants into a TypeScript module. This lets
 * the Kanna chat persona stay in sync with whatever the current docs say
 * without relying on outputFileTracingIncludes (which was triggering
 * Vercel's "symlinked directories" deployment check under pnpm).
 *
 * Runs as `prebuild` and `predev` in package.json so the output is fresh
 * on every build and every `pnpm dev` boot. The output file is also
 * committed so fresh checkouts work without prior generation.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();

function safeRead(rel: string): string {
  try {
    return readFileSync(join(ROOT, rel), "utf-8");
  } catch {
    return "";
  }
}

const readme = safeRead("README.md");
const handbook = safeRead("docs/handbook.md");

const out = `// Auto-generated by scripts/build-blog-corpus.ts. Do not edit by hand.
// Regenerated on every \`pnpm dev\` / \`pnpm build\`.

export const README_TEXT = ${JSON.stringify(readme)};

export const HANDBOOK_TEXT = ${JSON.stringify(handbook)};
`;

writeFileSync(join(ROOT, "src/lib/blog-corpus-text.ts"), out);
console.log(
  `[blog-corpus] wrote src/lib/blog-corpus-text.ts (README ${readme.length}B + handbook ${handbook.length}B)`,
);
